### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by nunojesus** [HeradoclesJose/GalaxyMusic#1]
Hello, do you need a logo for your player? Is you want I can make one for you for free.
I like contrbute to opensource projects like this and also I love music.

greetings

**Comment by HeradoclesJose** [comment]
Hi nuno.

Thanks for your offer but I will have to say that don't worry about it. GalaxyMusic was just a project for a college class we made 1 year ago and is not longer being developed... Lets say we we're just learning how to use things.

However, if you want, i have an outgoing open source project (codename: TheHermesProject) which it's final name will be BabelChat, consisting in a chat app to practice languages with native speakers with the mechanics of 15 minutes sessions and student and mentor roles.

If you are interested let me know!

BTW, thanks again for your wanting to help, I appreciate it!

**Comment by nunojesus** [comment]
Hello, I can do it, for sure, do you have any request? like colors?

Does this project have licence?

Greetings!

**Comment by nunojesus** [comment]
Hi, I can do that, just want to know if you have already a license?
